name: 'Terraform'
on: [push, pull_request]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@main

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform Init
      run: terraform init -backend-config="storage_account_name=colestfstateacc3786" -backend-config="container_name=colestfstate" -backend-config="resource_group_name=ColesTFStateRG" -backend-config="key=colestf.tfstate" -backend-config="sas_token=$TF_STATE_BLOB_SAS_TOKEN"
      working-directory: "./main"
      env:
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID}}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID}}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID}}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET}}

    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform Plan
      run: terraform plan -lock=false
      working-directory: "./main"
      env:
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID}}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID}}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID}}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET}}
    - name: Terraform Apply
      id: apply
      run: terraform apply -auto-approve -lock=false
      working-directory: "./main"
      env:
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID}}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID}}
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID}}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET}}